# Generated by Django 4.0.6 on 2022-07-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ifsc', models.CharField(max_length=250, null=True)),
                ('endpoint', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IFSC',
            fields=[
                ('bank', models.CharField(max_length=250)),
                ('ifsc', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('micr_code', models.CharField(max_length=250)),
                ('branch', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('district', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=250)),
            ],
        ),
    ]
